# Generated by Django 2.0.2 on 2018-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filosofia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_capa', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=20)),
                ('texto', models.CharField(blank=True, max_length=1000)),
                ('url_figura1', models.CharField(blank=True, max_length=200)),
                ('url_figura2', models.CharField(max_length=200)),
            ],
        ),
    ]
