# Generated by Django 2.0.2 on 2018-04-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='url_figura2',
            field=models.CharField(max_length=50),
        ),
    ]
