# Generated by Django 2.0.2 on 2018-04-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_auto_20180407_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='url_capa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historia',
            name='url_figura1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historia',
            name='url_figura2',
            field=models.CharField(max_length=200),
        ),
    ]
